[package]
name = "ez_excel_mgt"
version = "0.4.0"
edition = "2018"

[dependencies]
log = "0.4.22"
env_logger = "0.11.5"
pyo3 = { version = "0.18.0", features = ["extension-module"] }
polars = { version = "0.43.1", features = ["serde", "ipc"] }
umya-spreadsheet = "2.0.2"

[lib]
name = "ez_excel_mgt"
crate-type = ["cdylib"]

[package.metadata.maturin]
bindings = "pyo3"