name: Generate README.md

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install pypandoc

      - name: Install Pandoc
        run: python -c "import pypandoc; pypandoc.download_pandoc()"

      - name: Convert RST to Markdown
        run: |
          python -c "
          import pypandoc;
          output = pypandoc.convert_file('docs/readme.rst', 'md');
          with open('README.md', 'w') as md_file:
              md_file.write(output);
          print('Conversion completed')"

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m 'Convert RST to Markdown'
          git push